# Construção de dados

## Coletando dados

Muitas vezes, nosso dado de interesse não está imediatamente disponível e é necessário coletá-lo. Esse processo geralmente é realizado por engenheiros de dados, mas em equipes reduzidas é comum que esse trabalho fique para o analista de dados.

Existem várias formas de coletar dados e vamos focar na técnica de raspagem de dados ou Web Scrapping. Essa técnica corresponde a coletar os dados diretamente da Web através de bibliotecas que lerão páginas HTML e vão retirar os dados de lá. 

Vamos focar na raspagem de dados de tabelas HTML. Esses são dados que estão em tags \<table\> e geralmente aparecem como tabelas no navegador. Esse tipo de tabela pode ser obtido diretamente pela biblioteca Pandas, o que reduz bastante o trabalho envolvido na raspagem. 

## Limpeza e Organização dos dados

Uma vez que os dados foram coletados é possível que eles precisem ser limpos e organizados para que seja possível realizar a análise. Essa limpeza ou tratamento dos dados visa garantir sua integridade. Muitas vezes dados numéricos serão importados como texto e datas precisam ser reformatadas para poderem ser acessadas e processadas.

Esse processo de limpeza é realizado ao mesmo tempo que o conjunto de dados é organizado. Essa organização é o que garante que o conjunto de dados contém os dados de interesse e não contém colunas duplicadas ou dados que não possam ser utilizados. 

O conjunto de dados tratado e organizado é o que vamos salvar e compartilhar para a realização das análises. Um conjunto de dados bem construído é valioso e devemos ter muito cuidado para não perder as horas de trabalho que passamos limpando e organizando. Geralmente o conjunto de dados final é salvo em formato CSV, JSON em tabelas XLSX ou em bancos de dados para fácil acesso e processamento posterior.

In [1]:
import pandas as pd
import datetime

#### Limpeza de dados

Vamos começar tratando datas e organizando as colunas de um conjunto de dados.

In [2]:
# Vamos começar estudando a própria história do Python
# A URL a seguir contém uma tabela com informações sobre Python
url = 'https://en.wikipedia.org/wiki/History_of_Python'
# Vamos ler a tabela com Pandas. 
dfs = pd.read_html(url)
# O resultado é uma lista de DataFrames.
# Cada tabela da página é um elemento dessa lista.
print(len(dfs)) # Podemos ver quantas tabelas foram obtidas

1

In [3]:
# Vamos analisar a tabela obtida
dados = dfs[0]
dados.head()

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9[2],1991-02-20[2],1993-07-29[a][2],1993-07-29[a][2]
1,NaN,1.0.4[2],1994-01-26[2],1994-02-15[a][2],1994-02-15[a][2]
2,NaN,1.1.1[2],1994-10-11[2],1994-11-10[a][2],1994-11-10[a][2]
3,NaN,NaN,1995-04-13[2],Unsupported,Unsupported
4,NaN,NaN,1995-10-13[2],Unsupported,Unsupported

In [4]:
# Vemos que algumas colunas não parecem ter muitos valores válidos
# Vamos obter um sumário dos dados com a função info()
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Version                3 non-null      object
 1   Latest micro version   27 non-null     object
 2   Release date           31 non-null     object
 3   End of full support    31 non-null     object
 4   End of security fixes  31 non-null     object
dtypes: object(5)
memory usage: 1.3+ KB

In [5]:
# Temos 31 elementos e 5 colunas, mas apenas 3 possuem todos os elementos
# Como são poucos elementos, vamos visualizar o conjunto inteiro
dados # Observe as últimas entradas

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9[2],1991-02-20[2],1993-07-29[a][2],1993-07-29[a][2]
1,NaN,1.0.4[2],1994-01-26[2],1994-02-15[a][2],1994-02-15[a][2]
2,NaN,1.1.1[2],1994-10-11[2],1994-11-10[a][2],1994-11-10[a][2]
3,NaN,NaN,1995-04-13[2],Unsupported,Unsupported
4,NaN,NaN,1995-10-13[2],Unsupported,Unsupported
5,NaN,NaN,1996-10-25[2],Unsupported,Unsupported
6,NaN,1.5.2[42],1998-01-03[2],1999-04-13[a][2],1999-04-13[a][2]
7,NaN,1.6.1[42],2000-09-05[43],2000-09[a][42],2000-09[a][42]
8,NaN,2.0.1[44],2000-10-16[45],2001-06-22[a][44],2001-06-22[a][44]
9,NaN,2.1.3[44],2001-04-15[46],2002-04-09[a][44],2002-04-09[a][44]
10,NaN,2.2.3[44],2001-12-21[47],2003-05-30[a][44],2003-05-30[a][44]
11,NaN,2.3.7[44],2003-06-29[48],2008-03-11[a][44],2008-03-11[a][44]
12,NaN,2.4.6[44],2004-11-30[49],2008-12-19[a][44],2008-12-19[a][44]
13,NaN,2.5.6[44],2006-09-19[50],2011-05-26[a][44],2011-05-26[a][44]
14,NaN,2.6.9[27],2008-10-01[27],2010-08-24[b][27],2013-10-29[27]
15,NaN,2.7.18[32],2010-07-03[32],2020-01-01[c][32],2020-01-01[c][32]
16,NaN,3.0.1[44],2008-12-03[27],2009-06-27[51],2009-06-27[51]
17,NaN,3.1.5[52],2009-06-27[52],2011-06-12[53],2012-04-06[52]
18,NaN,3.2.6[54],2011-02-20[54],2013-05-13[b][54],2016-02-20[54]
19,NaN,3.3.7[55],2012-09-29[55],2014-03-08[b][55],2017-09-29[55]
20,NaN,3.4.10[56],2014-03-16[56],2017-08-09[57],2019-03-18[a][56]
21,NaN,3.5.10[58],2015-09-13[58],2017-08-08[59],2020-09-30[58]
22,NaN,3.6.15[60],2016-12-23[60],2018-12-24[b][60],2021-12-23[60]
23,NaN,3.7.13[61],2018-06-27[61],2020-06-27[b][61],2023-06-27[61]
24,NaN,3.8.13[62],2019-10-14[62],2021-05-03[b][62],2024-10[62]
25,NaN,3.9.13[63][needs update],2020-10-05[63],2022-05-17[b][63],2025-10[63][64]
26,3.10,3.10.7[65],2021-10-04[65],2023-05[65],2026-10[65]
27,NaN,3.11.0rc1[66],2022-10-03[66],2024-05[66],2027-10[66]
28,NaN,NaN,2023-10[64],2025-05[64],2028-10[64]
29,Legend:,Legend:,"Old versionOlder version, still maintainedLate...","Old versionOlder version, still maintainedLate...","Old versionOlder version, still maintainedLate..."
30,Italics indicates the latest micro version of ...,Italics indicates the latest micro version of ...,Italics indicates the latest micro version of ...,Italics indicates the latest micro version of ...,Italics indicates the latest micro version of ...

In [6]:
# As últimas linhas obtidas são a legenda da tabela e precisam ser excluídas
# A última linha corresponde a uma versão que não saiu, vamos eliminar também
dados = dados[0:28]
dados

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9[2],1991-02-20[2],1993-07-29[a][2],1993-07-29[a][2]
1,NaN,1.0.4[2],1994-01-26[2],1994-02-15[a][2],1994-02-15[a][2]
2,NaN,1.1.1[2],1994-10-11[2],1994-11-10[a][2],1994-11-10[a][2]
3,NaN,NaN,1995-04-13[2],Unsupported,Unsupported
4,NaN,NaN,1995-10-13[2],Unsupported,Unsupported
5,NaN,NaN,1996-10-25[2],Unsupported,Unsupported
6,NaN,1.5.2[42],1998-01-03[2],1999-04-13[a][2],1999-04-13[a][2]
7,NaN,1.6.1[42],2000-09-05[43],2000-09[a][42],2000-09[a][42]
8,NaN,2.0.1[44],2000-10-16[45],2001-06-22[a][44],2001-06-22[a][44]
9,NaN,2.1.3[44],2001-04-15[46],2002-04-09[a][44],2002-04-09[a][44]
10,NaN,2.2.3[44],2001-12-21[47],2003-05-30[a][44],2003-05-30[a][44]
11,NaN,2.3.7[44],2003-06-29[48],2008-03-11[a][44],2008-03-11[a][44]
12,NaN,2.4.6[44],2004-11-30[49],2008-12-19[a][44],2008-12-19[a][44]
13,NaN,2.5.6[44],2006-09-19[50],2011-05-26[a][44],2011-05-26[a][44]
14,NaN,2.6.9[27],2008-10-01[27],2010-08-24[b][27],2013-10-29[27]
15,NaN,2.7.18[32],2010-07-03[32],2020-01-01[c][32],2020-01-01[c][32]
16,NaN,3.0.1[44],2008-12-03[27],2009-06-27[51],2009-06-27[51]
17,NaN,3.1.5[52],2009-06-27[52],2011-06-12[53],2012-04-06[52]
18,NaN,3.2.6[54],2011-02-20[54],2013-05-13[b][54],2016-02-20[54]
19,NaN,3.3.7[55],2012-09-29[55],2014-03-08[b][55],2017-09-29[55]
20,NaN,3.4.10[56],2014-03-16[56],2017-08-09[57],2019-03-18[a][56]
21,NaN,3.5.10[58],2015-09-13[58],2017-08-08[59],2020-09-30[58]
22,NaN,3.6.15[60],2016-12-23[60],2018-12-24[b][60],2021-12-23[60]
23,NaN,3.7.13[61],2018-06-27[61],2020-06-27[b][61],2023-06-27[61]
24,NaN,3.8.13[62],2019-10-14[62],2021-05-03[b][62],2024-10[62]
25,NaN,3.9.13[63][needs update],2020-10-05[63],2022-05-17[b][63],2025-10[63][64]
26,3.10,3.10.7[65],2021-10-04[65],2023-05[65],2026-10[65]
27,NaN,3.11.0rc1[66],2022-10-03[66],2024-05[66],2027-10[66]

In [7]:
# Vamos eliminar as linhas 3, 4 e 5, que correspondem a versão unsupported
dados = dados.drop(index=[3,4,5]) # Vamos utilizar a função drop()
dados = dados.reset_index(drop=True)
dados

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9[2],1991-02-20[2],1993-07-29[a][2],1993-07-29[a][2]
1,NaN,1.0.4[2],1994-01-26[2],1994-02-15[a][2],1994-02-15[a][2]
2,NaN,1.1.1[2],1994-10-11[2],1994-11-10[a][2],1994-11-10[a][2]
3,NaN,1.5.2[42],1998-01-03[2],1999-04-13[a][2],1999-04-13[a][2]
4,NaN,1.6.1[42],2000-09-05[43],2000-09[a][42],2000-09[a][42]
5,NaN,2.0.1[44],2000-10-16[45],2001-06-22[a][44],2001-06-22[a][44]
6,NaN,2.1.3[44],2001-04-15[46],2002-04-09[a][44],2002-04-09[a][44]
7,NaN,2.2.3[44],2001-12-21[47],2003-05-30[a][44],2003-05-30[a][44]
8,NaN,2.3.7[44],2003-06-29[48],2008-03-11[a][44],2008-03-11[a][44]
9,NaN,2.4.6[44],2004-11-30[49],2008-12-19[a][44],2008-12-19[a][44]
10,NaN,2.5.6[44],2006-09-19[50],2011-05-26[a][44],2011-05-26[a][44]
11,NaN,2.6.9[27],2008-10-01[27],2010-08-24[b][27],2013-10-29[27]
12,NaN,2.7.18[32],2010-07-03[32],2020-01-01[c][32],2020-01-01[c][32]
13,NaN,3.0.1[44],2008-12-03[27],2009-06-27[51],2009-06-27[51]
14,NaN,3.1.5[52],2009-06-27[52],2011-06-12[53],2012-04-06[52]
15,NaN,3.2.6[54],2011-02-20[54],2013-05-13[b][54],2016-02-20[54]
16,NaN,3.3.7[55],2012-09-29[55],2014-03-08[b][55],2017-09-29[55]
17,NaN,3.4.10[56],2014-03-16[56],2017-08-09[57],2019-03-18[a][56]
18,NaN,3.5.10[58],2015-09-13[58],2017-08-08[59],2020-09-30[58]
19,NaN,3.6.15[60],2016-12-23[60],2018-12-24[b][60],2021-12-23[60]
20,NaN,3.7.13[61],2018-06-27[61],2020-06-27[b][61],2023-06-27[61]
21,NaN,3.8.13[62],2019-10-14[62],2021-05-03[b][62],2024-10[62]
22,NaN,3.9.13[63][needs update],2020-10-05[63],2022-05-17[b][63],2025-10[63][64]
23,3.10,3.10.7[65],2021-10-04[65],2023-05[65],2026-10[65]
24,NaN,3.11.0rc1[66],2022-10-03[66],2024-05[66],2027-10[66]

In [8]:
# Vamos agora limpar as colunas das marcações da Wikipedia
# Vemos que todas as colunas possuem dados entre colchetes []
# Vamos eliminar todos esses com a função split()
dados['Latest micro version'] = [dado.split('[')[0] for dado in dados['Latest micro version']]
dados

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9,1991-02-20[2],1993-07-29[a][2],1993-07-29[a][2]
1,NaN,1.0.4,1994-01-26[2],1994-02-15[a][2],1994-02-15[a][2]
2,NaN,1.1.1,1994-10-11[2],1994-11-10[a][2],1994-11-10[a][2]
3,NaN,1.5.2,1998-01-03[2],1999-04-13[a][2],1999-04-13[a][2]
4,NaN,1.6.1,2000-09-05[43],2000-09[a][42],2000-09[a][42]
5,NaN,2.0.1,2000-10-16[45],2001-06-22[a][44],2001-06-22[a][44]
6,NaN,2.1.3,2001-04-15[46],2002-04-09[a][44],2002-04-09[a][44]
7,NaN,2.2.3,2001-12-21[47],2003-05-30[a][44],2003-05-30[a][44]
8,NaN,2.3.7,2003-06-29[48],2008-03-11[a][44],2008-03-11[a][44]
9,NaN,2.4.6,2004-11-30[49],2008-12-19[a][44],2008-12-19[a][44]
10,NaN,2.5.6,2006-09-19[50],2011-05-26[a][44],2011-05-26[a][44]
11,NaN,2.6.9,2008-10-01[27],2010-08-24[b][27],2013-10-29[27]
12,NaN,2.7.18,2010-07-03[32],2020-01-01[c][32],2020-01-01[c][32]
13,NaN,3.0.1,2008-12-03[27],2009-06-27[51],2009-06-27[51]
14,NaN,3.1.5,2009-06-27[52],2011-06-12[53],2012-04-06[52]
15,NaN,3.2.6,2011-02-20[54],2013-05-13[b][54],2016-02-20[54]
16,NaN,3.3.7,2012-09-29[55],2014-03-08[b][55],2017-09-29[55]
17,NaN,3.4.10,2014-03-16[56],2017-08-09[57],2019-03-18[a][56]
18,NaN,3.5.10,2015-09-13[58],2017-08-08[59],2020-09-30[58]
19,NaN,3.6.15,2016-12-23[60],2018-12-24[b][60],2021-12-23[60]
20,NaN,3.7.13,2018-06-27[61],2020-06-27[b][61],2023-06-27[61]
21,NaN,3.8.13,2019-10-14[62],2021-05-03[b][62],2024-10[62]
22,NaN,3.9.13,2020-10-05[63],2022-05-17[b][63],2025-10[63][64]
23,3.10,3.10.7,2021-10-04[65],2023-05[65],2026-10[65]
24,NaN,3.11.0rc1,2022-10-03[66],2024-05[66],2027-10[66]

In [9]:
# Vamos repetir para cada coluna
dados['Release date'] = [dado.split('[')[0] for dado in dados['Release date']]
dados['End of full support'] = [dado.split('[')[0] for dado in dados['End of full support']]
dados['End of security fixes'] = [dado.split('[')[0] for dado in dados['End of security fixes']]
dados

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9,1991-02-20,1993-07-29,1993-07-29
1,NaN,1.0.4,1994-01-26,1994-02-15,1994-02-15
2,NaN,1.1.1,1994-10-11,1994-11-10,1994-11-10
3,NaN,1.5.2,1998-01-03,1999-04-13,1999-04-13
4,NaN,1.6.1,2000-09-05,2000-09,2000-09
5,NaN,2.0.1,2000-10-16,2001-06-22,2001-06-22
6,NaN,2.1.3,2001-04-15,2002-04-09,2002-04-09
7,NaN,2.2.3,2001-12-21,2003-05-30,2003-05-30
8,NaN,2.3.7,2003-06-29,2008-03-11,2008-03-11
9,NaN,2.4.6,2004-11-30,2008-12-19,2008-12-19
10,NaN,2.5.6,2006-09-19,2011-05-26,2011-05-26
11,NaN,2.6.9,2008-10-01,2010-08-24,2013-10-29
12,NaN,2.7.18,2010-07-03,2020-01-01,2020-01-01
13,NaN,3.0.1,2008-12-03,2009-06-27,2009-06-27
14,NaN,3.1.5,2009-06-27,2011-06-12,2012-04-06
15,NaN,3.2.6,2011-02-20,2013-05-13,2016-02-20
16,NaN,3.3.7,2012-09-29,2014-03-08,2017-09-29
17,NaN,3.4.10,2014-03-16,2017-08-09,2019-03-18
18,NaN,3.5.10,2015-09-13,2017-08-08,2020-09-30
19,NaN,3.6.15,2016-12-23,2018-12-24,2021-12-23
20,NaN,3.7.13,2018-06-27,2020-06-27,2023-06-27
21,NaN,3.8.13,2019-10-14,2021-05-03,2024-10
22,NaN,3.9.13,2020-10-05,2022-05-17,2025-10
23,3.10,3.10.7,2021-10-04,2023-05,2026-10
24,NaN,3.11.0rc1,2022-10-03,2024-05,2027-10

In [10]:
# Por fim, vamos tratar os dados de datas
# Vamos utilizar a coluna Release Date como exemplo
# O formato nessa coluna está aaaa-mm-dd
# Vamos utilizar a função split() novamente separando pelo -
# Vamos salvar o resultado como um objeto datetime
dados['Release date'] = [datetime.datetime(int(dado.split('-')[0]),int(dado.split('-')[1]),int(dado.split('-')[2])) for dado in dados['Release date']]
dados

,Version,Latest micro version,Release date,End of full support,End of security fixes
0,NaN,0.9.9,1991-02-20,1993-07-29,1993-07-29
1,NaN,1.0.4,1994-01-26,1994-02-15,1994-02-15
2,NaN,1.1.1,1994-10-11,1994-11-10,1994-11-10
3,NaN,1.5.2,1998-01-03,1999-04-13,1999-04-13
4,NaN,1.6.1,2000-09-05,2000-09,2000-09
5,NaN,2.0.1,2000-10-16,2001-06-22,2001-06-22
6,NaN,2.1.3,2001-04-15,2002-04-09,2002-04-09
7,NaN,2.2.3,2001-12-21,2003-05-30,2003-05-30
8,NaN,2.3.7,2003-06-29,2008-03-11,2008-03-11
9,NaN,2.4.6,2004-11-30,2008-12-19,2008-12-19
10,NaN,2.5.6,2006-09-19,2011-05-26,2011-05-26
11,NaN,2.6.9,2008-10-01,2010-08-24,2013-10-29
12,NaN,2.7.18,2010-07-03,2020-01-01,2020-01-01
13,NaN,3.0.1,2008-12-03,2009-06-27,2009-06-27
14,NaN,3.1.5,2009-06-27,2011-06-12,2012-04-06
15,NaN,3.2.6,2011-02-20,2013-05-13,2016-02-20
16,NaN,3.3.7,2012-09-29,2014-03-08,2017-09-29
17,NaN,3.4.10,2014-03-16,2017-08-09,2019-03-18
18,NaN,3.5.10,2015-09-13,2017-08-08,2020-09-30
19,NaN,3.6.15,2016-12-23,2018-12-24,2021-12-23
20,NaN,3.7.13,2018-06-27,2020-06-27,2023-06-27
21,NaN,3.8.13,2019-10-14,2021-05-03,2024-10
22,NaN,3.9.13,2020-10-05,2022-05-17,2025-10
23,3.10,3.10.7,2021-10-04,2023-05,2026-10
24,NaN,3.11.0rc1,2022-10-03,2024-05,2027-10

In [11]:
dados.dtypes

Version                          object
Latest micro version             object
Release date             datetime64[ns]
End of full support              object
End of security fixes            object
dtype: object

In [12]:
dados['Release date'][0].day

20

In [24]:
novos_1 = []
for item in dados['End of full support']:
    new = item.split(sep='-')
    new_2 = ''.join(new)
    if len(new_2) == 8:
        new_3 = int(new_2)
        datetime.datetime(new_3)
        novos_1.append(new_3)
    else:
        novos_1.append(new_2)

TypeError: function missing required argument 'month' (pos 2)

In [14]:
dados['End of full support'][0].day

AttributeError: 'str' object has no attribute 'day'

In [25]:
# Para organizar os dados, vamos utilizar outra variável
dados_limpos = pd.DataFrame() # Vamos começar com um DataFrame vazio
dados_limpos = dados[['Latest micro version','Release date']]
dados_limpos

   Latest micro version Release date
0                 0.9.9   1991-02-20
1                 1.0.4   1994-01-26
2                 1.1.1   1994-10-11
3                 1.5.2   1998-01-03
4                 1.6.1   2000-09-05
5                 2.0.1   2000-10-16
6                 2.1.3   2001-04-15
7                 2.2.3   2001-12-21
8                 2.3.7   2003-06-29
9                 2.4.6   2004-11-30
10                2.5.6   2006-09-19
11                2.6.9   2008-10-01
12               2.7.18   2010-07-03
13                3.0.1   2008-12-03
14                3.1.5   2009-06-27
15                3.2.6   2011-02-20
16                3.3.7   2012-09-29
17               3.4.10   2014-03-16
18               3.5.10   2015-09-13
19               3.6.15   2016-12-23
20               3.7.13   2018-06-27
21               3.8.13   2019-10-14
22               3.9.13   2020-10-05
23               3.10.7   2021-10-04
24            3.11.0rc1   2022-10-03

In [26]:
# Por fim, vamos salvar nossos dados
dados_limpos.to_csv('python-versões.csv')

In [27]:
# Vamos olhar outros exemplos
wiki = "https://en.wikipedia.org/wiki/List_of_films_based_on_Marvel_Comics"

In [28]:
df_marvel_site=pd.read_html(wiki,match='Box office')
len(df_marvel_site)
df_marvel = df_marvel_site[0]

In [29]:
df_marvel

                                          Title  \
                                          Title
0                               Howard the Duck
1                                         Blade
2                                         X-Men
3                                      Blade II
4                                    Spider-Man
..                                          ...
64                                      Morbius
65  Doctor Strange in the Multiverse of Madness
66                       Thor: Love and Thunder
67                                        Total
68                                      Average

                         Distributor(s) Release date(United States)  \
                         Distributor(s) Release date(United States)
0                    Universal Pictures              August 1, 1986
1                       New Line Cinema             August 21, 1998
2                      20th Century Fox               July 14, 2000
3                       New Line Cinema              March 22, 2002
4                         Sony Pictures                 May 3, 2002
..                                  ...                         ...
64                        Sony Pictures               April 1, 2022
65  Walt Disney Studios Motion Pictures                 May 6, 2022
66  Walt Disney Studios Motion Pictures                July 8, 2022
67                                Total                       Total
68                              Average                     Average

   Bud­get (mil­lions)           Box office gross[22]                   \
   Bud­get (mil­lions) Opening weekend(North America)    North America
0                  $37                     $5,070,136      $16,295,774
1                  $45                    $17,073,856      $70,087,718
2                  $75                    $54,471,475     $157,299,717
3                  $54                    $32,528,016      $82,348,319
4                 $139                   $114,844,116     $403,706,375
..                 ...                            ...              ...
64              $75–83                    $39,005,895      $73,865,530
65                $200                   $187,420,998     $411,331,607
66                $200                   $144,165,107     $342,513,832
67              $8,899                 $6,059,079,114  $16,670,500,647
68            $142.352                    $83,992,268     $228,139,366


   Other territories        Worldwide
0        $21,667,000      $37,962,774
1        $61,095,812     $131,183,530
2       $139,039,810     $296,339,527
3        $72,661,713     $155,010,032
4       $418,002,176     $821,708,551
..               ...              ...
64       $90,000,000     $163,865,530
65      $544,444,197     $955,755,804
66      $415,716,411     $758,230,243
67   $25,508,298,526  $42,179,305,055
68      $344,915,384     $573,054,859

[69 rows x 8 columns]

In [30]:
# Um exemplo com BeautifulSoup

res = requests.get("http://www.nationmaster.com/country-info/stats/Media/Internet-users")
soup = BeautifulSoup(res.content,'lxml')
table = soup.find_all('table')[0] 
df = pd.read_html(str(table))
print(df[0].to_json(orient='records'))

NameError: name 'requests' is not defined

In [31]:
df = pd.read_html(str(table))[0]
countries = df["COUNTRY"].tolist()
users = df["AMOUNT"].tolist()
countries

NameError: name 'table' is not defined