# Atividade Prática 2

Nessa atividade, vamos explorar conjuntos de dados distintos e será seu trabalho descrever os conjuntos dados.

In [6]:
import pandas as pd

dados1 = pd.read_csv('dados1.csv')
dados2 = pd.read_csv('dados2.csv')
dados3 = pd.read_csv('dados3.csv')

In [3]:
# Realize uma análise descritiva dos dados
# Deve conter as informações básicas do conjunto
# Número de elementos
# Nome e número de observações das colunas
# Estatística descritiva: média, desvio-padrão, correlação
dados1

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [7]:
dados1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object
 3   color       53940 non-null  object
 4   clarity     53940 non-null  object
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB

In [20]:
dados1.mean(numeric_only=True)

Unnamed: 0    26970.500000
carat             0.797940
depth            61.749405
table            57.457184
price          3932.799722
x                 5.731157
y                 5.734526
z                 3.538734
dtype: float64

In [28]:
dados1.carat.describe()

count    53940.000000
mean         0.797940
std          0.474011
min          0.200000
25%          0.400000
50%          0.700000
75%          1.040000
max          5.010000
Name: carat, dtype: float64

In [30]:
dados1[dados1["carat"] > 5]

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
27415,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98

In [13]:
dados1.std(numeric_only=True)

Unnamed: 0    15571.281097
carat             0.474011
depth             1.432621
table             2.234491
price          3989.439738
x                 1.121761
y                 1.142135
z                 0.705699
dtype: float64

In [15]:
dados1.corr()

,Unnamed: 0,carat,depth,table,price,x,y,z
Unnamed: 0,1.000000,-0.377983,-0.034800,-0.100830,-0.306873,-0.405440,-0.395843,-0.399208
carat,-0.377983,1.000000,0.028224,0.181618,0.921591,0.975094,0.951722,0.953387
depth,-0.034800,0.028224,1.000000,-0.295779,-0.010647,-0.025289,-0.029341,0.094924
table,-0.100830,0.181618,-0.295779,1.000000,0.127134,0.195344,0.183760,0.150929
price,-0.306873,0.921591,-0.010647,0.127134,1.000000,0.884435,0.865421,0.861249
x,-0.405440,0.975094,-0.025289,0.195344,0.884435,1.000000,0.974701,0.970772
y,-0.395843,0.951722,-0.029341,0.183760,0.865421,0.974701,1.000000,0.952006
z,-0.399208,0.953387,0.094924,0.150929,0.861249,0.970772,0.952006,1.000000

In [4]:
# Realize uma análise descritiva dos dados
# Deve conter as informações básicas do conjunto
# Número de elementos
# Nome e número de observações das colunas
# Estatística descritiva: média, desvio-padrão, correlação
dados2

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,highlight_fur_color,...,approaches,indifferent,runs_from,other_interactions,lat_long,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581),NaN,19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755),NaN,19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163),NaN,19,4,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466),NaN,19,4,19,13
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973),NaN,19,4,19,13
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883),NaN,19,4,19,13
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912),NaN,19,4,19,13
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025),NaN,19,4,19,13

In [8]:
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 36 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   long                                        3023 non-null   float64
 1   lat                                         3023 non-null   float64
 2   unique_squirrel_id                          3023 non-null   object
 3   hectare                                     3023 non-null   object
 4   shift                                       3023 non-null   object
 5   date                                        3023 non-null   int64
 6   hectare_squirrel_number                     3023 non-null   int64
 7   age                                         2902 non-null   object
 8   primary_fur_color                           2968 non-null   object
 9   highlight_fur_color                         1937 non-null   object
 10  combination_of_primary_and_highlight_color  3023 non-null   object
 11  color_notes                                 182 non-null    object
 12  location                                    2959 non-null   object
 13  above_ground_sighter_measurement            2909 non-null   object
 14  specific_location                           476 non-null    object
 15  running                                     3023 non-null   bool
 16  chasing                                     3023 non-null   bool
 17  climbing                                    3023 non-null   bool
 18  eating                                      3023 non-null   bool
 19  foraging                                    3023 non-null   bool
 20  other_activities                            437 non-null    object
 21  kuks                                        3023 non-null   bool
 22  quaas                                       3023 non-null   bool
 23  moans                                       3023 non-null   bool
 24  tail_flags                                  3023 non-null   bool
 25  tail_twitches                               3023 non-null   bool
 26  approaches                                  3023 non-null   bool
 27  indifferent                                 3023 non-null   bool
 28  runs_from                                   3023 non-null   bool
 29  other_interactions                          240 non-null    object
 30  lat_long                                    3023 non-null   object
 31  zip_codes                                   9 non-null      float64
 32  community_districts                         3023 non-null   int64
 33  borough_boundaries                          3023 non-null   int64
 34  city_council_districts                      3023 non-null   int64
 35  police_precincts                            3023 non-null   int64
dtypes: bool(13), float64(3), int64(6), object(14)
memory usage: 581.7+ KB

In [19]:
dados2.mean(numeric_only=True)

long                      -7.396718e+01
lat                        4.078085e+01
date                       1.011949e+07
hectare_squirrel_number    4.123718e+00
running                    2.414820e-01
chasing                    9.229242e-02
climbing                   2.176646e-01
eating                     2.514059e-01
foraging                   4.746940e-01
kuks                       3.374132e-02
quaas                      1.653986e-02
moans                      9.923917e-04
tail_flags                 5.127357e-02
tail_twitches              1.435660e-01
approaches                 5.888191e-02
indifferent                4.809792e-01
runs_from                  2.242805e-01
zip_codes                  1.182822e+04
community_districts        1.899603e+01
borough_boundaries         4.000000e+00
city_council_districts     1.907046e+01
police_precincts           1.300463e+01
dtype: float64

In [17]:
dados2.std(numeric_only=True)

long                           0.007726
lat                            0.010285
date                       42466.714959
hectare_squirrel_number        3.096492
running                        0.428053
chasing                        0.289486
climbing                       0.412726
eating                         0.433893
foraging                       0.499442
kuks                           0.180592
quaas                          0.127560
moans                          0.031492
tail_flags                     0.220592
tail_twitches                  0.350707
approaches                     0.235442
indifferent                    0.499721
runs_from                      0.417177
zip_codes                    995.983782
community_districts            0.234339
borough_boundaries             0.000000
city_council_districts         1.352253
police_precincts               0.224224
dtype: float64

In [18]:
dados2.corr()

,long,lat,date,hectare_squirrel_number,running,chasing,climbing,eating,foraging,kuks,...,tail_flags,tail_twitches,approaches,indifferent,runs_from,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
long,1.000000,0.906838,0.104391,-0.131927,0.034092,-0.037457,0.011311,-0.053743,-0.006438,0.057685,...,0.003152,-0.008117,-0.038302,-0.048323,0.135509,0.345111,0.017670,NaN,0.011493,0.098691
lat,0.906838,1.000000,0.161824,-0.121656,0.041225,-0.015951,0.005565,-0.056371,-0.005280,0.063737,...,0.002229,-0.006876,-0.038296,-0.075501,0.157491,0.616679,0.003251,NaN,-0.006286,0.080041
date,0.104391,0.161824,1.000000,-0.045330,0.037451,0.024388,-0.070891,-0.016823,0.013283,0.024082,...,-0.034538,-0.015369,0.025829,-0.031506,0.051473,0.567714,0.004310,NaN,-0.003694,0.025905
hectare_squirrel_number,-0.131927,-0.121656,-0.045330,1.000000,-0.005321,0.024911,-0.045676,0.026347,0.020212,0.019161,...,-0.018010,-0.073342,0.029947,0.003874,-0.028916,-0.095581,0.011622,NaN,-0.018915,-0.007021
running,0.034092,0.041225,0.037451,-0.005321,1.000000,0.025707,-0.055995,-0.123872,-0.220607,-0.006982,...,0.019521,0.029089,-0.016364,-0.116200,0.167285,-0.070459,-0.013533,NaN,0.036338,0.022821
chasing,-0.037457,-0.015951,0.024388,0.024911,0.025707,1.000000,-0.038022,-0.105754,-0.179526,0.060677,...,0.045055,0.022637,-0.040919,-0.002729,-0.061855,0.338567,-0.004353,NaN,0.012123,0.044392
climbing,0.011311,0.005565,-0.070891,-0.045676,-0.055995,-0.038022,1.000000,-0.111655,-0.297542,0.083457,...,-0.009952,-0.021641,-0.039993,-0.069767,0.048860,NaN,0.008937,NaN,-0.027489,-0.010896
eating,-0.053743,-0.056371,-0.016823,0.026347,-0.123872,-0.105754,-0.111655,1.000000,-0.008807,-0.028055,...,0.003568,0.047602,0.072071,0.069372,-0.011797,0.222812,0.013073,NaN,-0.030201,-0.015373
foraging,-0.006438,-0.005280,0.013283,0.020212,-0.220607,-0.179526,-0.297542,-0.008807,1.000000,-0.078581,...,-0.022759,0.058532,0.054887,0.132313,-0.056925,-0.422782,0.004796,NaN,-0.018182,-0.034412
kuks,0.057685,0.063737,0.024082,0.019161,-0.006982,0.060677,0.083457,-0.028055,-0.078581,1.000000,...,0.064542,-0.003363,-0.015611,-0.058887,0.035680,NaN,0.003166,NaN,-0.009738,-0.003860
quaas,0.057433,0.059990,0.018114,0.009897,-0.012570,0.093064,0.019590,-0.039282,-0.034980,0.191233,...,0.063930,-0.001319,-0.032438,-0.036592,-0.013767,NaN,0.002197,NaN,-0.006758,-0.002679
moans,0.027252,0.022720,0.029096,-0.008046,-0.017783,0.026248,0.034294,-0.018265,-0.008922,-0.005890,...,-0.007327,-0.012904,-0.007884,-0.030341,0.033428,NaN,0.000534,NaN,-0.001643,-0.000651
tail_flags,0.003152,0.002229,-0.034538,-0.018010,0.019521,0.045055,-0.009952,0.003568,-0.022759,0.064542,...,1.000000,-0.009636,0.005564,0.025360,0.054788,0.095174,-0.047272,NaN,0.023383,-0.024873
tail_twitches,-0.008117,-0.006876,-0.015369,-0.073342,0.029089,0.022637,-0.021641,0.047602,0.058532,-0.003363,...,-0.009636,1.000000,0.037852,-0.003295,0.051256,0.338567,-0.001116,NaN,0.002387,0.033622
approaches,-0.038302,-0.038296,0.025829,0.029947,-0.016364,-0.040919,-0.039993,0.072071,0.054887,-0.015611,...,0.005564,0.037852,1.000000,-0.187353,-0.067117,NaN,0.004238,NaN,-0.013035,-0.005167
indifferent,-0.048323,-0.075501,-0.031506,0.003874,-0.116200,-0.002729,-0.069767,0.069372,0.132313,-0.058887,...,0.025360,-0.003295,-0.187353,1.000000,-0.466830,-0.626724,0.016310,NaN,0.005167,-0.028746
runs_from,0.135509,0.157491,0.051473,-0.028916,0.167285,-0.061855,0.048860,-0.011797,-0.056925,0.035680,...,0.054788,0.051256,-0.067117,-0.466830,1.000000,0.626724,-0.031508,NaN,0.030636,0.049031
zip_codes,0.345111,0.616679,0.567714,-0.095581,-0.070459,0.338567,NaN,0.222812,-0.422782,NaN,...,0.095174,0.338567,NaN,-0.626724,0.626724,1.000000,-0.569128,NaN,-0.618277,0.547038
community_districts,0.017670,0.003251,0.004310,0.011622,-0.013533,-0.004353,0.008937,0.013073,0.004796,0.003166,...,-0.047272,-0.001116,0.004238,0.016310,-0.031508,-0.569128,1.000000,NaN,-0.355205,0.038136
borough_boundaries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city_council_districts,0.011493,-0.006286,-0.003694,-0.018915,0.036338,0.012123,-0.027489,-0.030201,-0.018182,-0.009738,...,0.023383,0.002387,-0.013035,0.005167,0.030636,-0.618277,-0.355205,NaN,1.000000,0.113516
police_precincts,0.098691,0.080041,0.025905,-0.007021,0.022821,0.044392,-0.010896,-0.015373,-0.034412,-0.003860,...,-0.024873,0.033622,-0.005167,-0.028746,0.049031,0.547038,0.038136,NaN,0.113516,1.000000

In [5]:
# Realize uma análise descritiva dos dados
# Deve conter as informações básicas do conjunto
# Número de elementos
# Nome e número de observações das colunas
# Estatística descritiva: média, desvio-padrão, correlação
dados3

,Arc,Start onChapter,TotalChapters,TotalPages,Manga%,Start onEpisode,TotalEpisodes,TotalMinutes(avg 24),Anime%
0,Romance Dawn Arc,1,7,178,0.9%,1,3,72,0.3%
1,Orange Town Arc,8,14,273,1.4%,4,5,120,0.5%
2,Syrup Village Arc,22,20,396,2.0%,9,10,240,1.0%
3,Baratie Arc,42,27,514,2.6%,19,12,288,1.2%
4,Arlong Park Arc,69,27,514,2.6%,31,15,360,1.5%
5,Buggy Side Story Arc,0,0,0,0.0%,46,2,48,0.2%
6,Loguetown Arc,96,5,100,0.5%,48,6,144,0.6%
7,Warship Island Arc,0,0,0,0.0%,54,8,192,0.8%
8,Reverse Mountain Arc,101,5,96,0.5%,62,2,48,0.2%
9,Whiskey Peak Arc,106,9,169,0.9%,64,4,96,0.4%
10,Koby and Helmeppo Arc,0,0,0,0.0%,68,2,48,0.2%
11,Little Garden Arc,115,15,288,1.5%,70,8,192,0.8%
12,Drum Island Arc,130,25,477,2.5%,78,14,336,1.4%
13,Alabasta Arc,155,63,1199,6.2%,92,39,936,3.8%
14,Post-Alabasta Arc,0,0,0,0.0%,131,5,120,0.5%
15,Goat Island Arc,0,0,0,0.0%,136,3,72,0.3%
16,Ruluka Island Arc,0,0,0,0.0%,139,5,120,0.5%
17,Jaya Arc,218,19,361,1.9%,144,9,216,0.9%
18,Skypiea Arc,237,66,1242,6.4%,153,43,1032,4.2%
19,G-8 Arc,0,0,0,0.0%,196,11,264,1.1%
20,Long Ring Long Land Arc,303,19,365,1.9%,207,15,360,1.5%
21,Ocean's Dream Arc,0,0,0,0.0%,220,5,120,0.5%
22,Foxy's Return Arc,0,0,0,0.0%,225,2,48,0.2%
23,Water 7 Arc,322,53,1009,5.2%,229,35,840,3.4%
24,Enies Lobby Arc,375,56,1060,5.4%,264,49,1176,4.8%
25,Post-Enies Lobby Arc,431,11,209,1.1%,313,13,312,1.3%
26,Ice Hunter Arc,0,0,0,0.0%,326,11,264,1.1%
27,Thriller Bark Arc,442,48,912,4.7%,337,45,1080,4.4%
28,Spa Island Arc,0,0,0,0.0%,382,3,72,0.3%
29,Sabaody Archipelago Arc,490,24,456,2.3%,385,21,504,2.0%
30,Special Historical Arc,0,0,0,0.0%,406,2,48,0.2%
31,Amazon Lily Arc,514,11,209,1.1%,408,14,336,1.4%
32,Impel Down Arc,525,25,473,2.4%,422,31,744,3.0%
33,Little East Blue Arc,0,0,0,0.0%,426,4,96,0.4%
34,Marineford Arc,550,31,529,2.7%,457,33,792,3.2%
35,Post-War Arc,581,17,317,1.6%,490,27,648,2.6%
36,Return to Sabaody Arc,598,5,98,0.5%,517,6,144,0.6%
37,Fishman Island Arc,603,51,933,4.8%,523,52,1248,5.1%
38,Z's Ambition Arc,0,0,0,0.0%,575,4,96,0.4%
39,Punk Hazard Arc,654,46,856,4.4%,579,47,1128,4.6%
40,Caesar Retrieval Arc,0,0,0,0.0%,626,3,72,0.3%
41,Dressrosa Arc,700,102,1830,9.4%,629,118,2832,11.5%
42,Silver Mine Arc,0,0,0,0.0%,747,4,96,0.4%
43,Zou Arc,802,23,397,2.0%,751,29,696,2.8%
44,Marine Rookie Arc,0,0,0,0.0%,780,3,72,0.3%
45,Whole Cake Island Arc,825,78,1349,6.9%,783,95,2280,9.2%
46,Levely Arc,903,6,100,0.5%,878,12,288,1.2%
47,Wano Country Arc: Act 1,909,16,278,1.4%,890,26,624,2.5%
48,Cidre Guild Arc,0,0,0,0.0%,895,2,48,0.2%
49,Wano Country Arc: Act 2,925,33,560,2.9%,918,41,984,4.0%
50,Wano Country Arc: Act 3,958,99,1709,8.8%,959,70,1680,6.8%

In [9]:
dados3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Arc                   51 non-null     object
 1   Start onChapter       51 non-null     int64
 2   TotalChapters         51 non-null     int64
 3   TotalPages            51 non-null     int64
 4   Manga%                51 non-null     object
 5   Start onEpisode       51 non-null     int64
 6   TotalEpisodes         51 non-null     int64
 7   TotalMinutes(avg 24)  51 non-null     int64
 8   Anime%                51 non-null     object
dtypes: int64(6), object(3)
memory usage: 3.7+ KB

In [21]:
dados3.mean(numeric_only=True)

Start onChapter         268.823529
TotalChapters            20.705882
TotalPages              381.490196
Start onEpisode         354.745098
TotalEpisodes            20.156863
TotalMinutes(avg 24)    483.764706
dtype: float64

In [23]:
dados3.std(numeric_only=True)

Start onChapter         317.019287
TotalChapters            26.133728
TotalPages              471.266268
Start onEpisode         291.209742
TotalEpisodes            24.345326
TotalMinutes(avg 24)    584.287826
dtype: float64

In [24]:
dados3.corr()

,Start onChapter,TotalChapters,TotalPages,Start onEpisode,TotalEpisodes,TotalMinutes(avg 24)
Start onChapter,1.000000,0.595637,0.575794,0.648648,0.684749,0.684749
TotalChapters,0.595637,1.000000,0.998524,0.236850,0.929732,0.929732
TotalPages,0.575794,0.998524,1.000000,0.204692,0.918775,0.918775
Start onEpisode,0.648648,0.236850,0.204692,1.000000,0.393252,0.393252
TotalEpisodes,0.684749,0.929732,0.918775,0.393252,1.000000,1.000000
TotalMinutes(avg 24),0.684749,0.929732,0.918775,0.393252,1.000000,1.000000

In [26]:
# O que cada conjunto de dados representa?
print("O primeiro conjunto de dados contém informações sobre diamantes, como qualidade do corte, peso em quilates, cor, claridade e profundidade.")
print("O segundo conjunto de dados contém informações de rastreamento de esquilos, como id do esquilo, localização de cada um e o horário em que a posição foi tomada pelo chip de rastreamento.")
print("O terceiro conjunto de dados contém informações sobre o mangá e anime One Piece, separados por arcos da história.")

O primeiro conjunto de dados contém informações sobre diamantes, como qualidade do corte, peso em quilates, cor, claridade e profundidade.
O segundo conjunto de dados contém informações de rastreamento de esquilos, como id do esquilo, localização de cada um e o horário em que a posição foi tomada pelo chip de rastreamento.
O terceiro conjunto de dados contém informações sobre o mangá e anime One Piece, separados por arcos da história.